### ISSUE TITLE
Support of css helper

### ISSUE THREAD

**Issue by denisborovikov** [styled-components/webstorm-styled-components#30] opened 2017-09-15 10:20 UTC
Doesn't work properly with css helper https://www.styled-components.com/docs/api (scroll down)

Dosn't work:
![image](https://user-images.githubusercontent.com/831065/30478144-661f0230-9a42-11e7-8d96-76db1495bec9.png)

Works as expected:
![image](https://user-images.githubusercontent.com/831065/30478150-6c7e6ad0-9a42-11e7-8fb2-8865ce46ee0f.png)

**Comment by undeadcat** [comment] 2017-09-15 10:26
Hi!
What version are you using? and 
Could you, possibly, share the whole file that reproduces this issue, *as text*?

This very much looks like a duplicate of https://github.com/styled-components/webstorm-styled-components/issues/19, which was addressed.
Also, it seems to work for me:
![image](https://user-images.githubusercontent.com/7509842/30478362-6cf4efda-9a19-11e7-8ce9-fc218c9fc742.png)

**Comment by denisborovikov** [comment] 2017-09-15 10:28
Hi! Thanks, just found this issue by myself. Webstorm didn't show the update for some reason, reinstalled manually, it works now. Thank you!

**Closed** 2017-09-15 10:29 UTC
